config/routes.rb
Beerminder::Application.routes.draw do
  get "drank_beers/new"
  get "drank_beers/create"
  get "drank_beers/destroy"
  get "home/index"

  resource :user_session
  resource :drank_beer

  root :controller => "home", :action => "index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/drank_beer.rb
class DrankBeer < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
  has_many :drank_beers
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper :all
  helper_method :current_user_session, :current_user
  filter_parameter_logging :password, :password_confirmation
  
  private
    def current_user_session
      return @current_user_session if defined?(@current_user_session)
      @current_user_session = UserSession.find
    end
    
    def current_user
      return @current_user if defined?(@current_user)
      @current_user = current_user_session && current_user_session.record
    end
    
    def require_user
      unless current_user
        store_location
        flash[:notice] = "You must be logged in to access this page"
        redirect_to new_user_session_url
        return false
      end
    end

    def require_no_user
      if current_user
        store_location
        flash[:notice] = "You must be logged out to access this page"
        redirect_to root_url
        return false
      end
    end
    
    def store_location
      session[:return_to] = request.request_uri
    end
    
    def redirect_back_or_default(default)
      redirect_to(session[:return_to] || default)
      session[:return_to] = nil
    end
 end

app/controllers/drank_beers_controller.rb
require 'date'
class DrankBeersController < ApplicationController
  def new
  end

  def create
    beer = DrankBeer.new(params[:drank_beer])
    beer.user = current_user
    beer.timestamp = Time.now
    beer.save!

    @drank_beer = beer
  end

  def destroy
  end

  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @drank_beer = DrankBeer.new
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => :destroy
  
  # Prompt for login
  def new
    @user_session = UserSession.new
  end
  
  # Process Login Attempt
  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:notice] = "Login successful!"
      redirect_back_or_default root_url
    else
      render :action => :new
    end
  end
  
  # Logout
  def destroy
    current_user_session.destroy
    flash[:notice] = "Logout successful!"
    redirect_back_or_default new_user_session_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drank_beers_helper.rb
module DrankBeersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/drank_beers/create.html.erb
<h1>DrankBeers#create</h1>
<p>Find me in app/views/drank_beers/create.html.erb</p>
Quantity: <%= @drank_beer.quantity %>

app/views/drank_beers/destroy.html.erb
<h1>DrankBeers#destroy</h1>
<p>Find me in app/views/drank_beers/destroy.html.erb</p>

app/views/drank_beers/new.html.erb
<h1>DrankBeers#new</h1>
<p>Find me in app/views/drank_beers/new.html.erb</p>

app/views/drank_beers/show.html.erb
<h1>DrankBeers#show</h1>
<p>Find me in app/views/drank_beers/show.html.erb</p>
<p>Quantity: <%= @drank_beer.quantity.quantity %></p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<% unless current_user %>
  <%= link_to "Login", new_user_session_url %>
<% else %>
  <% form_for @drank_beer, :url => drank_beer_path do |f| %>
    <%= f.label :quantity %><br />
    <%= f.text_field :quantity %><br />
    <br />
    <%= f.submit "Drink!" %>
  <% end %>
<%= link_to "Logout", user_session_path, :method => :delete, :confirm => "Are you sure you want to logout?" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Beerminder</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/user_sessions/new.html.erb
<h1>Login</h1>
<% form_for @user_session, :url => user_session_path do |f| %>
  <%#= f.error_messages %>
  <%= f.label :login %><br />
  <%= f.text_field :login %><br />
  <br />
  <%= f.label :password %><br />
  <%= f.password_field :password %><br />
  <br />
  <%= f.check_box :remember_me %><%= f.label :remember_me %><br />
  <br />
  <%= f.submit "Login" %>
<% end %>